<?php

return [
    [
        "idDrink" => "12402",
        "strDrink" => "Tom Collins",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Collins glass",
        "strInstructions" => "In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a collins glass almost filled with ice cubes. Add the club soda. Stir and garnish with the cherry and the orange slice.",
        "strInstructionsIT" => "In uno shaker riempito a metà con cubetti di ghiaccio, unisci il gin, il succo di limone e lo zucchero.Mescolate e guarnite con la ciliegia e la fetta d'arancia.Filtrare in un bicchiere collins pieno di cubetti di ghiaccio.Aggiungi la soda club.Agitare bene.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg",
        "strIngredient1" => "Gin",
        "strIngredient2" => "Lemon juice",
        "strIngredient3" => "Sugar",
        "strIngredient4" => "Club soda",
        "strIngredient5" => "Maraschino cherry",
        "strIngredient6" => "Orange",
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "2 oz ",
        "strMeasure2" => "1 oz ",
        "strMeasure3" => "1 tsp superfine ",
        "strMeasure4" => "3 oz ",
        "strMeasure5" => "1 ",
        "strMeasure6" => "1 ",
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => "https://commons.wikimedia.org/wiki/File:Tom_Collins.jpg",
        "strImageAttribution" => "Will Shenton",
    ],
    [
        "idDrink" => "178360",
        "strDrink" => "Lemon Elderflower Spritzer",
        "strTags" => "Summer, Fresh, Refreshing",
        "strCategory" => "Cocktail",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Pour all ingredients over ice, stir and enjoy!\r\n",
        "strInstructionsIT" => null,
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/125w0o1630407389.jpg",
        "strIngredient1" => "Elderflower cordial",
        "strIngredient2" => "Vodka",
        "strIngredient3" => "Soda Water",
        "strIngredient4" => "Fresh Lemon Juice",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "2 tsp",
        "strMeasure2" => "1 shot",
        "strMeasure3" => "1/3 cup",
        "strMeasure4" => "Top",
        "strMeasure5" => "",
        "strMeasure6" => "",
        "strMeasure7" => "",
        "strMeasure8" => null,
        
        "strImageSource" => "https://www.instagram.com/p/CNLYC2_sdlk",
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "11472",
        "strDrink" => "Hawaiian Cocktail",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Cocktail glass",
        "strInstructions" => "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" => "Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/ujoh9x1504882987.jpg",
        "strIngredient1" => "Gin",
        "strIngredient2" => "Triple sec",
        "strIngredient3" => "Pineapple juice",
        "strIngredient4" => null,
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "2 oz ",
        "strMeasure2" => "1/2 oz ",
        "strMeasure3" => "1 tblsp ",
        "strMeasure4" => null,
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "14071",
        "strDrink" => "Belgian Blue",
        "strTags" => null,
        "strCategory" => "Soft Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Just pour all ingredients in the glass and stir...",
        "strInstructionsIT" => "Basta versare tutti gli ingredienti nel bicchiere e mescolare.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/jylbrq1582580066.jpg",
        "strIngredient1" => "Vodka",
        "strIngredient2" => "Coconut liqueur",
        "strIngredient3" => "Blue Curacao",
        "strIngredient4" => "Sprite",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "2 cl ",
        "strMeasure2" => "1 cl ",
        "strMeasure3" => "1 cl ",
        "strMeasure4" => "Fill with ",
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "16984",
        "strDrink" => "Radioactive Long Island Iced Tea",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Collins Glass",
        "strInstructions" => "Pour all ingredients over ice in a very tall glass. Sip cautiously.",
        "strInstructionsIT" => "Versare tutti gli ingredienti sul ghiaccio in un bicchiere molto alto.\r\nSorseggia con cautela.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/rdvqmh1503563512.jpg",
        "strIngredient1" => "Rum",
        "strIngredient2" => "Vodka",
        "strIngredient3" => "Tequila",
        "strIngredient4" => "Gin",
        "strIngredient5" => "Triple sec",
        "strIngredient6" => "Chambord raspberry liqueur",
        "strIngredient7" => "Midori melon liqueur",
        "strIngredient8" => "Malibu rum",
        
        "strMeasure1" => "1 oz ",
        "strMeasure2" => "1 oz ",
        "strMeasure3" => "1 oz ",
        "strMeasure4" => "1 oz ",
        "strMeasure5" => "1 oz ",
        "strMeasure6" => "1 oz ",
        "strMeasure7" => "1 oz ",
        "strMeasure8" => "1 oz ",
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "16985",
        "strDrink" => "Shot-gun",
        "strTags" => null,
        "strCategory" => "Shot",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Shot glass",
        "strInstructions" => "Pour one part Jack Daniels and one part Jim Beam into shot glass then float Wild Turkey on top.",
        
        "strInstructionsDE" => "Gießen Sie ein Teil Jack Daniels und ein Teil Jim Beam in ein Schnapsglas und lassen Sie Wild Turkey darauf treiben.",
        "strInstructionsIT" => "Versare una parte di Jack Daniels e una parte diJim Beam nel bicchierino da shot, infine versare il Wild Turkey.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/2j1m881503563583.jpg",
        "strIngredient1" => "Jim Beam",
        "strIngredient2" => "Jack Daniels",
        "strIngredient3" => "Wild Turkey",
        "strIngredient4" => null,
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "1 part ",
        "strMeasure2" => "1 part ",
        "strMeasure3" => "1 oz ",
        "strMeasure4" => null,
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "14195",
        "strDrink" => "Snowball",
        "strTags" => "Christmas",
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Place one ice cube in the glass and add 1 1/2 oz of Advocaat. Fill up the glass with lemonade and decorate with a slice of lemon. Serve at once.",
        "strInstructionsIT" => "Riempite il bicchiere con la limonata e decorate con una fetta di limone.\r\n",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/7ibfs61504735416.jpg",
        "strIngredient1" => "Advocaat",
        "strIngredient2" => "Lemonade",
        "strIngredient3" => "Lemon",
        "strIngredient4" => "Ice",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "1 1/2 oz ",
        "strMeasure2" => "8-10 oz cold ",
        "strMeasure3" => "1 slice ",
        "strMeasure4" => "cubes",
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "12656",
        "strDrink" => "Banana Strawberry Shake",
        "strTags" => null,
        "strCategory" => "Shake",
        "strAlcoholic" => "Non alcoholic",
        "strGlass" => "Highball Glass",
        "strInstructions" => "Blend all together in a blender until smooth.",
        "strInstructionsIT" => "Frullate tutto insieme in un frullatore fino a che non risulti liscio.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/vqquwx1472720634.jpg",
        "strIngredient1" => "Strawberries",
        "strIngredient2" => "Banana",
        "strIngredient3" => "Yoghurt",
        "strIngredient4" => "Milk",
        "strIngredient5" => "Honey",
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "1/2 lb frozen ",
        "strMeasure2" => "1 frozen ",
        "strMeasure3" => "1 cup plain ",
        "strMeasure4" => "1 cup ",
        "strMeasure5" => " to taste\n",
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "11320",
        "strDrink" => "Dragonfly",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "In a highball glass almost filled with ice cubes, combine the gin and ginger ale. Stir well. Garnish with the lime wedge.",
        "strInstructionsIT" => "In un bicchiere highball quasi riempito con cubetti di ghiaccio, unire il gin e la ginger ale. Mescolare bene. Guarnire con lo spicchio di lime.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/uc63bh1582483589.jpg",
        "strIngredient1" => "Gin",
        "strIngredient2" => "Ginger ale",
        "strIngredient3" => "Lime",
        "strIngredient4" => null,
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "1 1/2 oz ",
        "strMeasure2" => "4 oz ",
        "strMeasure3" => "1 ",
        "strMeasure4" => null,
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "idDrink" => "178318",
        "strDrink" => "747 Drink",
        "strTags" => null,
        "strCategory" => "Cocktail",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Fill a Collins glass with ice.\r\nPour in vodka, lime cordial, and cranberry juice.\r\nFill up with Sprite.\r\nGarnish with a Lime wheel or some cranberries",
        "strInstructionsIT" => "\r\nRiempi un bicchiere Collins di ghiaccio.\r\nVersare la vodka, lo sciroppo di lime e il succo di mirtillo rosso.\r\nRiempi con Sprite.\r\nGuarnire con una fetta di lime o dei mirtilli rossi",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/i9suxb1582474926.jpg",
        "strIngredient1" => "Vodka",
        "strIngredient2" => "Roses sweetened lime juice",
        "strIngredient3" => "Cranberry Juice",
        "strIngredient4" => "Sprite",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,
        
        "strMeasure1" => "1 oz",
        "strMeasure2" => "1 oz",
        "strMeasure3" => "1 oz",
        "strMeasure4" => "Top",
        "strMeasure5" => "",
        "strMeasure6" => "",
        "strMeasure7" => "",
        "strMeasure8" => null,
        
        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
];
